"""
core/theories/discovered/ — Dynamically discovered theory modules.

Theory modules in this package were generated by forge/theory_builder.py from
academic papers found by the research pipeline and approved by a consultant.

These modules are subject to the same interface requirements as built-in theories:
    - Inherit from TheoryBase
    - Use @register_theory("theory_id")
    - Declare DOMAINS class attribute
    - Implement update(env, agents, tick) -> dict[str, float]

Provenance is preserved in data/theories/pending/{pending_id}.json alongside
the source paper metadata, smoke test results, and review record.

Built-in theories live in core/theories/. Discovered theories live here.
SimRunner, TheoryMapper, and the catalog API treat both identically once registered.
"""
